import os

class AzerothCoreDBWriter:
    """
    A class to generate SQL scripts for an AzerothCore 3.3.5a database.
    """
    def __init__(self):
        # Lists of IDs for races, classes, and proficiencies.
        # These can be modified here to support different server versions or custom content.
        self.races = [1, 2, 3, 4, 5, 6, 7, 8, 10, 11]
        self.classes = [1, 2, 3, 4, 5, 6, 7, 8, 9, 11]
        self.proficiencies = [
            196,  # One-Handed Axes
            197,  # Two-Handed Axes
            5011, # Bows
            5012, # Crossbows
            5013, # Daggers
            5014, # Fist Weapons
            5015, # Guns
            198,  # One-Handed Maces
            199,  # Two-Handed Maces
            200,  # Polearms
            201,  # One-Handed Swords
            202,  # Two-Handed Swords
            227,  # Staves
            228,  # Thrown
            5009, # Wands
            674,  # Offhand Dagger
            675,  # Offhand Fist Weapon
            676,  # Offhand Axe
            677,  # Offhand Mace
            678,  # Offhand Sword
        ]

    def generate_all_weapon_proficiencies_sql(self, filename):
        """
        Generates a SQL file to grant all weapon proficiencies to all races and classes.

        Args:
            filename (str): The name of the SQL file to be created.
        """
        # A critical warning about the DELETE statement
        print(f"Generating SQL script: '{filename}'")
        print("\n" + "="*50)
        print("  WARNING: This script will remove all default starting skills.")
        print("           Always back up your database before running this!")
        print("="*50 + "\n")

        with open(filename, "w") as sql_file:
            sql_file.write("-- This script grants all weapon proficiencies to all playable races and classes.\n")
            sql_file.write("-- Generated by a Python script.\n")
            sql_file.write("-- WARNING: This script will remove all default starting actions. Make sure to back up your database!\n\n")
            sql_file.write("DELETE FROM `playercreateinfo_action`;\n\n")
            sql_file.write("INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`) VALUES\n")

            all_lines = []
            for race in self.races:
                for azeroth_class in self.classes:
                    for spell_id in self.proficiencies:
                        line = f"({race}, {azeroth_class}, 99, {spell_id}, 0)"
                        all_lines.append(line)

            for i, line in enumerate(all_lines):
                if i < len(all_lines) - 1:
                    sql_file.write(f"  {line},\n")
                else:
                    sql_file.write(f"  {line};\n")

        print(f"SQL script '{filename}' generated successfully!")
        print(f"File saved to: {os.path.abspath(filename)}")

